- hosts: all
  tasks:
    - name: Start zuul_console daemon.
      zuul_console:
- hosts: localhost
  tasks:
    - zuul-git:
        data:
          zuul:
            log_url: http://zuul-webinar.codilime.com/logs/{{ zuul.build }}
